import {readFile,writeFile} from 'node:fs/promises';
import {LEAGUES} from './leagues.mjs';
import {vulnerability} from './core.mjs';
const SPORTS_DB='https://www.thesportsdb.com/api/v1/json/123',FOOTBALL_DATA='https://football-data.co.uk',output=new URL('../dist/data/matches.json',import.meta.url);
const season=(()=>{const now=new Date(),y=now.getUTCFullYear(),start=now.getUTCMonth()<6?y-1:y;return `${String(start).slice(-2)}${String(start+1).slice(-2)}`})();
async function getText(url){const response=await fetch(url,{headers:{'user-agent':'BottomBetScanner/1.0 (+public GitHub project)'}});if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.text()}
async function getJson(url){for(let attempt=0;attempt<3;attempt++){const text=await getText(url);if(text.trim()){const data=JSON.parse(text);await new Promise(resolve=>setTimeout(resolve,1200));return data}await new Promise(resolve=>setTimeout(resolve,2000*(attempt+1)))}throw new Error('réponse vide')}
function csvRows(text){if(!text.trim())return[];const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/),headers=parseCsvLine(lines.shift());return lines.map(line=>{const values=parseCsvLine(line),row={};headers.forEach((h,i)=>row[h]=values[i]??'');return row})}
function parseCsvLine(line){const out=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){out.push(value);value=''}else value+=c}out.push(value);return out}
function dateFromParts(date,time='12:00'){const [d,m,y]=date.split('/').map(Number),[h,min]=time.split(':').map(Number);return new Date(Date.UTC(y,m-1,d,h||12,min||0))}
function formFor(team,results){return results.filter(g=>g.HomeTeam===team||g.AwayTeam===team).slice(-5).map(g=>g.FTHG===g.FTAG?'D':((g.HomeTeam===team&&Number(g.FTHG)>Number(g.FTAG))||(g.AwayTeam===team&&Number(g.FTAG)>Number(g.FTHG)))?'W':'L').reverse()}
function tableFromResults(results){const map=new Map(),team=n=>{if(!map.has(n))map.set(n,{team:n,p:0,gd:0,pts:0});return map.get(n)};for(const g of results){if(g.FTR==='')continue;const h=team(g.HomeTeam),a=team(g.AwayTeam),hg=Number(g.FTHG),ag=Number(g.FTAG);h.p++;a.p++;h.gd+=hg-ag;a.gd+=ag-hg;if(hg>ag)h.pts+=3;else if(ag>hg)a.pts+=3;else{h.pts++;a.pts++}}return [...map.values()].sort((a,b)=>b.pts-a.pts||b.gd-a.gd||a.team.localeCompare(b.team)).map((x,i)=>({...x,rank:i+1}))}
const aliases=new Map([['manchester city','man city'],['manchester united','man united'],['nottingham forest',"nott'm forest"],['wolverhampton wanderers','wolves'],['brighton and hove albion','brighton'],['inter milan','inter'],['paris saint-germain','paris sg']]);
const key=name=>{const raw=String(name).toLowerCase(),canonical=aliases.get(raw)||raw;return canonical.replace(/[^a-z0-9]/g,'')};
function emit(league,table,events,forms){const size=table.length,byTeam=new Map(table.map(x=>[key(x.team),x]));return events.flatMap(event=>{if(new Date(event.kickoff)<new Date(Date.now()-3600000))return[];const home=byTeam.get(key(event.home)),away=byTeam.get(key(event.away)),low=[home,away].filter(Boolean).sort((a,b)=>b.rank-a.rank)[0];if(!low||low.rank<size-4)return[];const venue=low===home?'home':'away',opponent=venue==='home'?away:home;if(!opponent)return[];const form=(forms.get(low.team)||[]).slice(0,5);while(form.length<5)form.push('D');return[{league:league.name,bottomTeam:low.team,bottomRank:low.rank,tableSize:size,opponent:opponent.team,opponentRank:opponent.rank,kickoff:event.kickoff,venue,form,vulnerability:vulnerability({rank:low.rank,tableSize:size,form,venue,opponentRank:opponent.rank})}]})}
async function fromSportsDb(league){const [eventData,resultsText]=await Promise.all([getJson(`${SPORTS_DB}/eventsnextleague.php?id=${league.sportsDb}`),getText(`${FOOTBALL_DATA}/mmz4281/${season}/${league.dataCode}.csv`)]),results=csvRows(resultsText),table=tableFromResults(results),forms=new Map(table.map(x=>[x.team,formFor(x.team,results)])),events=eventData.events||[];if(table.length<8)throw new Error('résultats insuffisants');return emit(league,table,events.map(x=>({home:x.strHomeTeam,away:x.strAwayTeam,kickoff:x.strTimestamp.endsWith('Z')?x.strTimestamp:`${x.strTimestamp}Z`})),forms)}
let fixtureRows;
async function fromFootballData(league){if(!fixtureRows)fixtureRows=csvRows(await getText(`${FOOTBALL_DATA}/fixtures.csv`).catch(()=>''));const results=csvRows(await getText(`${FOOTBALL_DATA}/mmz4281/${season}/${league.dataCode}.csv`)),table=tableFromResults(results),forms=new Map(table.map(x=>[x.team,formFor(x.team,results)])),events=fixtureRows.filter(x=>x.Div===league.dataCode).map(x=>({home:x.HomeTeam,away:x.AwayTeam,kickoff:dateFromParts(x.Date,x.Time).toISOString()}));return emit(league,table,events,forms)}
const matches=[],errors=[];
for(const league of LEAGUES){let rows=[],sportsDbWorked=false;if(league.sportsDb){try{rows=await fromSportsDb(league);sportsDbWorked=true}catch(error){errors.push(`${league.name} (TheSportsDB): ${error.message}`)}}if(!sportsDbWorked){try{rows=await fromFootballData(league)}catch(error){errors.push(`${league.name} (Football-Data): ${error.message}`)}}matches.push(...rows);await new Promise(resolve=>setTimeout(resolve,1000))}
const unique=[...new Map(matches.map(x=>[`${x.league}|${x.bottomTeam}|${x.kickoff}`,x])).values()].sort((a,b)=>new Date(a.kickoff)-new Date(b.kickoff));
if(!unique.length){const old=JSON.parse(await readFile(output,'utf8'));console.error('Aucun match collecté. Dernières données conservées.');console.error(errors.join('\n'));if(!old.matches?.length)process.exitCode=1;else process.exitCode=2}else{await writeFile(output,JSON.stringify({generatedAt:new Date().toISOString(),source:'TheSportsDB + Football-Data.co.uk',errors,matches:unique},null,2)+'\n');console.log(`${unique.length} matchs enregistrés; ${errors.length} championnats en erreur.`)}
